### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by pawamoy** [tarkatronic/django-excel-response#10]
Some questions I asked myself reading your README:

- is this app meant to edit excel files in the browser?
- are the spreadsheets automatically rendered?
- or do we have to write the templates? in this case, could you provide a minimal example?
- does it work in admin interface?
- can the spreadsheets be downloaded?

Anyway, interesting app :+1:

**Comment by tarkatronic** [comment]
Do you have some specific recommendations for fixes to the README? I find myself at a bit of a loss, aside from building out a whole RTD, which I had thought might be overkill.

**Comment by pawamoy** [comment]
You could maybe add a `Features` section just after the `Installation` one, and answer to the questions above in this section.

**Comment by pawamoy** [comment]
Feel free to reopen :slightly_smiling_face:
