### ISSUE TITLE
Getting "IndexError: list index out of range" when list is empty

### ISSUE THREAD

**Issue by hussaintamboli** [tarkatronic/django-excel-response#14]
My django queryset is returning empty queryset. So when I create `ExcelResponse` for it, I get `IndexError: list index out of range`.

I should be able to get empty excel file right?

In fact, I did this

    return ExcelResponse([], 'test')

and I get the same exception.

**Comment by tarkatronic** [comment]
@hussaintamboli Thank you for the bug report. I will look into this as soon as I get a chance!

**Comment by tarkatronic** [comment]
@hussaintamboli I have released version 2.0.2 last night to take care of this issue. Thank you again for the bug report. :+1:

**Comment by hussaintamboli** [comment]
Thanks.
