### ISSUE TITLE
extensions not appended to filename in Firefox

### ISSUE THREAD

**Issue by AzMoo** [tarkatronic/django-excel-response#28]
When the filename is set in the content-disposition header on these two lines:

https://github.com/tarkatronic/django-excel-response/blob/7096d597f654cb9e58395de32969674994146654/excel_response/response.py#L61

https://github.com/tarkatronic/django-excel-response/blob/7096d597f654cb9e58395de32969674994146654/excel_response/response.py#L66

The extension is outside of the quotation marks. This is working OK for Google Chrome but firefox just ignores the file extension entirely. I believe it should be inside the quotation marks. 

Happy to do a pull request if you need it.

**Comment by tarkatronic** [comment]
@AzMoo Oh wow, that definitely does look like a bug! I would happy accept a pull request if you can put one together!
